### ISSUE TITLE
 Uncaught exception 'InvalidArgumentException' with message 'Invalid code'

### ISSUE THREAD

**Issue by Sidjain8599** [spjoshis/File-Uploader-To-Google-Drive-PHP#1]
I am trying your code to upload files to google drive but i am getting these errors : 

Enter verification code: 
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid code' in C:\xampp\htdocs\fileup\vendor\google\apiclient\src\Google\Client.php:176 Stack trace: #0 C:\xampp\htdocs\fileup\upload.php(44): Google_Client->fetchAccessTokenWithAuthCode('') #1 C:\xampp\htdocs\fileup\upload.php(78): GoogleDrive->getClient() #2 C:\xampp\htdocs\fileup\index.php(4): GoogleDrive->upload('files/', 'photo.gif') #3 {main} thrown in C:\xampp\htdocs\fileup\vendor\google\apiclient\src\Google\Client.php on line 176

And also i am getting one more error on same page :+1: 

Open the following link in your browser:link here

Please solve it and reply me as soon as possible.

Thanks in advance

**Comment by spjoshis** [comment]
Seems like the format for access token described in above issue does not match with the format been generated in new API. Please verify your `drive-php-upload.json` and `client_secret.json` files. That might be the reason why API is throwing thisexception.

**Comment by chobela** [comment]
Hi I am also getting the same error. SO should I re arrange my json file from new api to match your json arangement?

**Comment by spjoshis** [comment]
Yes
